### PR TITLE
Capture miscellaneous event keywords.

### PR DESCRIPTION
**Pull request by rkrater**
I needed a way to get miscellaneous event keywords that aren't being captured. It would return an array of these keywords. 

For example Microsoft Exchange Server adds : 
- X-MICROSOFT-CDO-INTENDEDSTATUS
- X-MICROSOFT-CDO-BUSYSTATUS
- X-MICROSOFT-CDO-IMPORTANCE

### CODE REVIEW

**Comment by jarofgreen** [comment]
This is great, thanks very much!

So one concern I have is that say we introduce some code to parse out INTENDEDSTATUS later, then we would also have to make sure Misc still contains that variable. Some users might be relying on it being in Misc, so to remove it from Misc would in effect be a backwards incompatible API break. So to avoid that, we'd have to store the value in 2 places. 

With that in mind, I wonder if Misc is the best title. Questions might arise in people's mind: "What fields are and aren't in Misc?" 

Maybe it should be called Raw and just all raw data is stuffed in there, with a corresponding RawKeywordProperties\* to.

(By Keyword Properties I mean the "TZID=Europe/London" bit in "DTEND;TZID=Europe/London:20150212T100000". I should probably read the RFC and see if that has a proper name.)

Also, can one keyword legitimately occur twice in one event? Should getRaw("X") return an array of values? RFC reading time!

But basically, this will definitely go in in some way, I'm just going to think about the best name and operation for a bit.

Do you have an example ICS file I can put into the tests and write a very simple test for this?

(And I assume your happy with BSD license?)

Thanks!

(Also, do tell me what your using it for, curios!)

**Comment by jarofgreen** [comment]
http://www.ietf.org/rfc/rfc2445.txt

Section 4.1 - what I've called a "Keyword Properties" is just called a param, I think. I'll just leave that name.

Section 4.1.2 - ah, multiple values are sometimes allowed.

Ok, so I'm leaning towards a "Raw" variable that returns lists for each one. Will ponder.

**Comment by rkrater** [comment]
I think your Raw idea would work great. I stumbled across your project when looking for a ical program i could use to sync the files into a database that feeds our website and mobile app.

**Comment by jarofgreen** [comment]
https://github.com/JMB-Technology-Limited/ICalDissect/commit/f985346f3a9d2d26fd3903e02d64aed18272e31f Done as raw. Additions to what is discussed:

All keywords in upper case. In the spec this is true anyway and if you get a situation where you have "description" or "DESCRIPTION" you'd probably prefer that to be hidden from you, and if you need to tell the difference it's all gone crazy anyway.

getRaw can be passed null to get all data, or passed a keyword to get those values. In the latter case it always returns an array, even if there was no data - so an empty array. This will still evaluate as false in a simple comparison check but will not crash if you pass this directly to a foreach.  Most likely, people will probably do:

```
$x = $event->getRaw('X-CUSTOM');
if ($x) {
    ..... $x[0];
}
```

Which should work grand to!

Sounds good?

**Comment by jarofgreen** [comment]
v1.2.0 released

**Pull request closed without merging**
